### ISSUE TITLE
Exception continuously thrown and logged

### ISSUE THREAD

**Issue by curtisblackwell** [edalzell/statamic-mailchimp#39]
Mailchimp is writing an exception to my logs every second. Here's the exception:

```
[2020-08-17 16:44:28] local.ERROR: Uncaught Symfony\Component\Finder\Exception\DirectoryNotFoundException: The "/Users/cblackwell/Sites/highland/vendor/edalzell/mailchimp/resources/views" directory does not exist. in /Users/cblackwell/Sites/highland/vendor/symfony/finder/Finder.php:589
Stack trace:
#0 /Users/cblackwell/Sites/highland/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(444): Symfony\Component\Finder\Finder->in('/Users/cblackwe...')
#1 Command line code(37): Illuminate\Filesystem\Filesystem->files('/Users/cblackwe...')
#2 Command line code(66): getViews('/Users/cblackwe...', Object(Illuminate\Filesystem\Filesystem), 'mailchimp', '::')
#3 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Symfony\\Component\\Finder\\Exception\\DirectoryNotFoundException: The \"/Users/cblackwell/Sites/highland/vendor/edalzell/mailchimp/resources/views\" directory does not exist. in /Users/cblackwell/Sites/highland/vendor/symfony/finder/Finder.php:589
Stack trace:
#0 /Users/cblackwell/Sites/highland/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(444): Symfony\\Component\\Finder\\Finder->in('/Users/cblackwe...')
#1 Command line code(37): Illuminate\\Filesystem\\Filesystem->files('/Users/cblackwe...')
#2 Command line code(66): getViews('/Users/cblackwe...', Object(Illuminate\\Filesystem\\Filesystem), 'mailchimp', '::')
#3 {main}
  thrown at /Users/cblackwell/Sites/highland/vendor/symfony/finder/Finder.php:589)
[stacktrace]
#0 {main}
"} 
```

And here's my config:

```php
<?php

return [

    /*
     * If you want to add to your mailchimp audience when a user registers, set this to `true`
     */
    'add_new_users' => false,

    /*
     * The form submissions to add to your Mailchimp Audiences
     */
    'forms' => [
        [
            /*
            * A MailChimp audience id. Check the MailChimp docs if you don't know
            * how to get this value:
            * https://mailchimp.com/help/find-audience-id/.
            */
            'audience_id' => 'real-id-in-my-config',

            /*
            * if you need consent before you can subscribe someone, set this to `true`
            */
            'check_consent' => false,

            /*
            * if you're checking for consent, which field is it? Defaults to `'consent'`
            */
            'consent_field' => 'consent',

            /*
            * handle of the form to listen for
            */
            'form' => 'downloadable',

            /*
            * See https://mailchimp.com/help/manage-audience-signup-form-fields/ for details on
            * Mailchimp merge fields
            */
            'merge_fields' => [
                [
                    'tag'        => 'FNAME',
                    'field_name' => 'first_name',
                ],
                [
                    'tag'        => 'LNAME',
                    'field_name' => 'last_name',
                ],
                [
                    'tag'        => 'LANDING',
                    'field_name' => 'url',
                ],
                [
                    'tag'        => 'COMPANY',
                    'field_name' => 'company',
                ],
                [
                    'tag'        => 'JOB_TITLE',
                    'field_name' => 'job_titlez',
                ],
            ],

            /*
            * To have single opt in only, which I don't recommend, set this to `true`.
            * See: https://mailchimp.com/help/single-opt-in-vs-double-opt-in/ for details
            */
            'disable_opt_in' => true,
        ],
    ],
];
```

I also have `MAILCHIMP_APIKEY` set in my `.env`.

**Comment by edalzell** [comment]
Looked at that error closer, it's looking for a folder that shouldn't exist. Is there some place you're trying to load a mail chimp view? Search for `mailchimp::` and see what you find @curtisblackwell.

**Comment by edalzell** [comment]
Also, Statamic v3 was released and I updated Mailchimp to make it compatible, perhaps that will knock this loose?

**Comment by edalzell** [comment]
@curtisblackwell this still occurring?

**Comment by curtisblackwell** [comment]
Hey, sorry for the delay. Was never trying to load a Mailchimp view. I'm pretty sure that was Statamic trying to load an addon settings view or something of that nature. Notice it was looking in your vendor directory.

This appears to be resolved now, though.

**Comment by curtisblackwell** [comment]
Turns out I had uninstalled the add-on. This is still happening now that I've re-installed it. Is there other info I can provide to help debug? Or we can schedule some time to look at it together if that's helpful.

**Comment by edalzell** [comment]
Is this v2 or v3 @curtisblackwell ?

**Comment by curtisblackwell** [comment]
v3. Latest version of Mailchimp, 3.0.2 for Statamic. Nothing in the changelog suggests anything that would affect addons for Statamic, but I'll go ahead and try updating.

**Comment by curtisblackwell** [comment]
Yep, updating makes no difference. It seems to me like Statamic expects addons to have a view for the CP, and your addon just doesn't have one.

**Comment by edalzell** [comment]
can't reproduce
